import "./Auth/Login/LoginAndOnboarding.cy";
import "./Dao/NewProposal/Member.cy";
import "./Dao/NewProposal/Standard.cy";
import "./Dao/Proposals/Multi Select/BulkAction.cy";
import "./Dao/Proposals/Multi Select/NoBulkAction.cy";
import "./Dao/Proposals/SortBy.cy";
import "./Dao/ViewProposal/Actions/Execute.cy";
import "./Dao/ViewProposal/Actions/Vote.cy";
import "./Dao/ViewProposal/ViewProposal.cy";
import "./MoodsAndPosts/MoodsAndPosts.cy";
import "./User/ProfileEdit.cy";
