export const aestheticList = [
    // "Arty Fashion CSM Queer Feminine Hyperluxury",
    // "Global Emergence RetroFuturism",
    // "Internet Trap Teenager CryptoBro",
    // "Minimal New Age Raw Green Nature Zen",
    // "telfarglobal",
    // "bypseudonym",
    "ancient tribe",
    "arty",
    "bauhaus",
    "black beauty",
    "cinema",
    "csm",
    "cyber",
    "fatal model",
    "goth",
    "margiela vintage",
    "vintage",
    "y2k"
]